name: Mechanics
main: dev._2lstudios.mechanics.Mechanics
version: 0.0.1
author: LinsaFTW
api-version: '1.13'
softdepend:
  - "PlaceholderAPI"
  - "ProtocolLib"
commands:
  cobblestone:
    aliases:
      - cobble
    description: "Toggles cobblestone pickup"
  dirt:
    description: "Toggles dirt pickup"
  magnet:
    description: "Toggles magnet mode"