name: GameMechanics
main: dev._2lstudios.mechanics.GameMechanics
version: 0.0.1
author: LinsaFTW
api-version: '1.13'
softdepend:
  - "PlaceholderAPI"
  - "ProtocolLib"
commands:
  cobblestone:
    aliases:
      - cobble
    description: "Toggle cobblestone pickup"
  dirt:
    description: "Toggle dirt pickup"
  magnet:
    description: "Toggle magnet mode"